// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nospiovdvuegghrtgehf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vc3Bpb3ZkdnVlZ2docnRnZWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxOTY5MDgsImV4cCI6MjA2MDc3MjkwOH0.bLXtdBKSkqQffUvI1YzqwOPXJ2E9ShbzYZEVmaKZS6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);